version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: database_container
    environment:
      MYSQL_ROOT_PASSWORD: 123         
      MYSQL_DATABASE: taskdb                 
      MYSQL_USER: user                   
      MYSQL_PASSWORD: 456              
    ports:
      - "3310:3306"                     
    volumes:
      - my_data:/var/lib/mysql    
    networks:
      - my_network                   

  adminpanel:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: database                    
      MYSQL_ROOT_PASSWORD: 123    
    ports:
      - "8090:80"               
    networks:
      - my_network                 

volumes:
  my_data:   

networks:
  my_network:     
